### PR TITLE
Updates for Scala 2.13

### PR DESCRIPTION
**Pull request by travisbrown**
I'm moving this pull request from [here](https://github.com/sangria-graphql/sangria/pull/453) as discussed [here](https://github.com/sangria-graphql/sangria/issues/446#issuecomment-546281588).

All of our Sangria dependencies here (including the test ones) are now published with Scala 2.13 support. There are some breaking changes, so I've bumped the major version to 2.0.0. Please see the original PR for details.

I think we should publish this as a 2.0.0-M1 today, and plan to publish a 2.0.0 in a week or two if no major issues come up.

### CODE REVIEW

**Comment by travisbrown** [comment]
@yanns What do you think about merging this and publishing it as a milestone release today? That gives people an easier way to try it out, but also leaves us some space to sneak other changes into 2.0.0 if we decide we want them.

**Comment by travisbrown** [comment]
I've seen a few of these flaky failures in CI today in other projects:
```
[error] java.lang.ArrayIndexOutOfBoundsException: 52857
[error] scala.tools.asm.ClassReader.readLabel(ClassReader.java:2262)
[error] scala.tools.asm.ClassReader.createLabel(ClassReader.java:2269)
```
It doesn't look familiar to me, and I'm not sure what's going on. Previously restarting has fixed it, so I'm trying that here.

**Review by yanns — APPROVED** [review]
too many changes... 😭 

I agree to go with a RC release first.

**Comment by travisbrown** [comment]
@yanns Great, thanks! I'll publish it shortly. I think it'd be better to go with a milestone than a release candidate (to give other contributors a chance to move over PRs without the pressure of a release candidate), so it'll be 2.0.0-M1, if that sounds good to you.

**Comment by yanns** [comment]
@travisbrown `2.0.0-M1` sounds perfect.

**Pull request merged**
